### ISSUE TITLE
Error after updating HA to 2022.5.3

### ISSUE THREAD

**Issue by kristina258** [gontxomde/ha-seconds-history-stats#1]
Hi, 

I updated HA to 2022.5.3 and history_stats_seconds threw the following error:

```This error originated from a custom integration.

Logger: homeassistant.helpers.entity
Source: custom_components/history_stats_second/sensor.py:233
Integration: history_stats_second (documentation)
First occurred: 12:28:20 (26 occurrences)
Last logged: 12:33:51

Update for sensor.tv_time_on fails
Update for sensor.door_opened fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 515, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 743, in async_device_update
    raise exc
  File "/config/custom_components/history_stats_second/sensor.py", line 219, in async_update
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/history_stats_second/sensor.py", line 233, in _update
    last_state = history.get_state(self.hass, start, self._entity_id)
AttributeError: module 'homeassistant.components.recorder.history' has no attribute 'get_state'
```

Could anyone give me an advice how to fix it ?

Thank you

**Comment by electron-mike** [comment]
Unfortunately, I don't have a solution, but I'm having the same problem.

**Comment by gontxomde** [comment]
I looked at this issue last week and it seems the structure of sensors has completely changed. I should look much more deep to know how to do this.

I don't think I will be able to do this in the short term. I'm sorry.
